### ISSUE TITLE
Exception thrown when parsing the job output

### ISSUE THREAD

**Issue by mardukbp** [lars-sh/jes-client#23]
The call `jesClient.getJobDetails(job)` threw the following exception:

```
de.larssh.jes.parser.JesFtpFileEntryParserException: Expected [^ {9}ID  STEPNAME PROCSTEP C DDNAME   (BYTE|REC)-COUNT( COMMENT)? *$] as sub title line, got [STEP, PROC, CPUT, and ELAPT unknown ].
```

Maybe it would be better to have a method that returns the raw response and a method for parsing the response, which takes a regex as argument. That way the user can first see the response and based on it build the appropriate regex.

EDIT: I did some research and it occurred to me that maybe it is related to #3?

**Comment by mardukbp** [comment]
Thank you for addressing it so fast! Today I executed the job and I extracted the outputs. I did not check the JES interface level, but I noticed that the first line of the output begins with JES2.

At first the job did not run because the name had an invalid character. Next week I will check the output that does not match the regex from JesClient and will report back with a regex for it. Then JesClient could try to match the current regex, if it fails try to match the new regex and if that fails just let it pass through.

**Comment by mardukbp** [comment]
@lars-sh I took a look at your fix and you already implemented the regex OR. Version 0.9.3 has been working well. Could you publish it on Maven? Thank you!

**Comment by lars-sh** [comment]
@mardukbp, I just release version 0.9.3. It should be available within the next few hours.

**Comment by mardukbp** [comment]
Perfect! Already used it. Thank you Lars!

**Comment by mardukbp** [comment]
@lars-sh I stumbled upon another output line that needs special handling:

```java
de.larssh.jes.parser.JesFtpFileEntryParserException: Expected [^ {9}ID  STEPNAME PROCSTEP C DDNAME   (BYTE|REC)-COUNT( COMMENT)? *$] as sub title line, got [0 spool files ].
```

**Comment by lars-sh** [comment]
@mardukbp, again, thanks for your input.
Might you check out the latest commit, please?

Btw., I'd appreciate new GitHub issues for further findings to simplify handling them :)

**Comment by mardukbp** [comment]
Thanks @lars-sh! Yes, sorry. I was too hasty.
